### ISSUE TITLE
Breaks pseudo-selectors

### ISSUE THREAD

**Issue by bjeanes** [johnotander/postcss-class-repeat#1]
Hi, thanks for this plugin! It's solving a real problem for me in a legacy codebase where I am introducing new CSS but want to limit its application.

However, it is breaking `:before`/`:after` selectors for me. In fact, your README actually demonstrates the problem in its example:

``` css
.foo.foo.bar.bar,
.baz:before.baz:before {
  color: tomato;
}
```

I think most people, myself included, would expect the following output:

``` css
.foo.foo.bar.bar,
.baz.baz:before {
  color: tomato;
}
```

Given this is in the README, I do wonder if this is intentional and useful for a scenario I can't imagine. But on the chance it's an oversight, I thought I'd open an issue in case the fix is reasonably straight forward.

**Comment by bjeanes** [comment]
Or, perhaps:

``` css
.foo.foo.bar.bar,
.baz.baz:before:before {
  color: tomato;
}
```
